# Generated by Django 5.1.6 on 2025-03-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('supplier', 'supplier'), ('customer', 'customer'), ('delivery', 'delivery')], default='customer', max_length=25),
        ),
    ]
