# Generated by Django 5.1.6 on 2025-03-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_buy', '0004_remove_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
