# Generated by Django 5.1.6 on 2025-03-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_buy', '0004_alter_order_customer_alter_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
