# Generated by Django 5.1.6 on 2025-03-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_buy', '0005_alter_orderitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total',
        ),
    ]
