# Generated by Django 5.1.6 on 2025-03-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_buy', '0005_alter_purchasedelivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_status',
        ),
    ]
