# Generated by Django 5.1.6 on 2025-03-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_buy', '0006_remove_product_available_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='quantity',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
