# Generated by Django 5.1.6 on 2025-03-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_buy', '0007_alter_orderitem_quantity_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='quantity',
            field=models.IntegerField(max_length=10),
        ),
    ]
