# Generated by Django 5.1.6 on 2025-03-27 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_buy', '0010_alter_orderitem_quantity_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Easy_buy.order'),
        ),
        migrations.AlterField(
            model_name='purchasedelivery',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='Easy_buy.purchase'),
        ),
    ]
