# Generated by Django 5.1.6 on 2025-03-17 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_buy', '0011_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('cancelled', 'cancelled')], default='pending', max_length=25),
        ),
        migrations.CreateModel(
            name='Purchase_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Easy_buy.product')),
                ('purchase_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Easy_buy.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseAccept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.CharField(choices=[('pending', 'pending'), ('accept', 'accept'), ('cancel', 'cancel')], default='pending', max_length=25)),
                ('purchase_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Easy_buy.purchase')),
            ],
        ),
    ]
