# Generated by Django 5.1.6 on 2025-03-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_buy', '0012_remove_purchase_product_remove_purchase_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase_Items',
            new_name='Purchase_Item',
        ),
    ]
