# Generated by Django 5.1.6 on 2025-03-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_buy', '0013_rename_purchase_items_purchase_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
