# Generated by Django 5.1.6 on 2025-03-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_buy', '0014_remove_product_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_item',
            old_name='purchase_detail',
            new_name='purchase',
        ),
        migrations.RenameField(
            model_name='purchaseaccept',
            old_name='purchase_details',
            new_name='purchase',
        ),
    ]
