# Generated by Django 5.1.6 on 2025-03-19 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Easy_buy', '0015_rename_purchase_detail_purchase_item_purchase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery',
            new_name='OrderDelivery',
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_items', to='Easy_buy.purchase'),
        ),
        migrations.CreateModel(
            name='PurchaseDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'assigned'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='assigned', max_length=25)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Easy_buy.purchase')),
            ],
        ),
        migrations.DeleteModel(
            name='PurchaseAccept',
        ),
    ]
